Use recognizeable string `id`
When trying to upload the proguard mapping file with Firebase CLI, we get an error:

```
[CRASHLYTICS LOG DEBUG] Extracting mappingFileId from resource file: /Users/sherozn/src/client-android/android_res.xml
java.lang.IllegalArgumentException: Resource file does not contain a valid mapping file id: <path to the xml file>
```

According to the documentation we need to:
1. Generate unique mapping file ID in the xml file
2. Upload the proguard mapping file and associate it with the mapping file ID.

CLI docs: https://firebase.google.com/docs/cli#crashlytics-commands